### ISSUE TITLE
Make Mac release

### ISSUE THREAD

**Issue by Zamiell** [Basement-Renovator/Basement-Renovator#161]
Maybe using pyinstaller?

**Comment by budjmt** [comment]
alright, when this is ready are you willing to handle tweaking the code for mac? I don't have one to test with

**Comment by Zamiell** [comment]
Sure

**Comment by budjmt** [comment]
We can now build Windows. Further Mac experimentation is needed.

**Comment by Zamiell** [comment]
given that isaac doesn't even work on mac anymore, lets close this
