### ISSUE TITLE
Inconsistent XML files since commit fa5e835b2493cd9d0e85025b3f5e14645371996b

### ISSUE THREAD

**Issue by Zamiell** [Basement-Renovator/Basement-Renovator#231]
1) XML files probably shouldn't have a mix of tabs and spaces. If we want to use extra spaces to align the XML attributes, then we should be consistent and use spaces everywhere.
2) If we want to use extra spaces to align the XML attributes, then we should have it in all 5 RoomType XMLs instead of just some of them. Specifically, it looks like Rebirth, Afterbirth, Afterbirth+, have spacing, but Antibirth and Repentance don't.

**Comment by budjmt** [comment]
1. It's common even in workflows that use tabs to only use them for leading whitespace and use spaces for alignment afterward. Happy to move to spaces overall though.
2. Sure, I don't see that as a priority though. If you'd like to do that go ahead
