### ISSUE TITLE
Tool not opening

### ISSUE THREAD

**Issue by SaiashaDoesTheSeck** [Basement-Renovator/Basement-Renovator#266]
Every time i try to open the program it shows an error and says im missing this
![image](https://user-images.githubusercontent.com/74738320/126694981-9dc39885-ce3b-4e98-8d91-6c2c82842346.png)
i tried downloading the dll and putting them on the tool's folder but it doesnt work

**Comment by Zamiell** [comment]
try on a freshly installed windows 10 with no other software present on the system

**Comment by SaiashaDoesTheSeck** [comment]
> try on a freshly installed windows 10 with no other software present on the system

Problem is I don't have windows 10, and I use windows 7.
I tried to get virtual machines to work in the past but no progress

**Comment by Zamiell** [comment]
win 7 is end of life and not supported by microsoft nor us

**Comment by SaiashaDoesTheSeck** [comment]
> win 7 is end of life and not supported by microsoft nor us

Alright thanks for trying to help me tho
Have a good day
