### ISSUE TITLE
Game runs sped-up when starting test run with high refresh rate

### ISSUE THREAD

**Issue by guwahavel** [Basement-Renovator/Basement-Renovator#271]
If you have a refresh rate higher than 60 Hz, when you start a test run in Basement Renovator the game will be significantly sped up. This is fixed by pausing and unpausing the game but it's still rather annoying. Its definitely tied to refresh rate since the issue came and went and I switched between 60 and 120 Hz.

**Comment by Zamiell** [comment]
does it happen with the vanilla room editor

**Comment by guwahavel** [comment]
Just tried it and yes, the vanilla Room Editor has the same issue.

**Comment by Zamiell** [comment]
BR uses the same "instapreview" command line flag that the other room editor does, so this isn't an issue with BR, its an issue with the flag / the game. report it to kil, not to us.

for your use case, don't use instapreview and instead use the other testing mods (e.g. Replace Stage)
