### ISSUE TITLE
Renaming a room with F2 duplicates the room ID in the name

### ISSUE THREAD

**Issue by jubbalub** [Basement-Renovator/basement-renovator#292]
Renaming a room with the F2 hotkey creates a duplicate of the room ID at the beginning of the room name. I don't think this is intended behavior, as it doesn't happen when renaming it via double-click.

![mANhr3llWi](https://user-images.githubusercontent.com/12634749/192696742-5a0134cf-7775-4aac-93a4-644dd01da87b.gif)

**Comment by budjmt** [comment]
Fixed in https://github.com/Basement-Renovator/basement-renovator/commit/d7cf4e75771ac1e10f6c16ea4cb70cbf0aa5fc35
