### ISSUE TITLE
MainWindow object window has no attribute 'floorinfo'

### ISSUE THREAD

**Issue by JudeForNothing** [Basement-Renovator/basement-renovator#303]
This error started persisting since I got the latest version of Basement Renovator. When I place and select certain custom enemies I made, it crashes and does this crash traceback:
![image](https://user-images.githubusercontent.com/83236309/236110441-0778b6cb-1f24-402c-9c60-a2a27d127696.png)

I assumed it was only my entities because only certain enemies I made crashes.

But when testing my room even without those entities that make me crash when I place and select them, it crashes, showing a similar but different traceback
![image](https://user-images.githubusercontent.com/83236309/236110698-561e1c30-a514-47c9-8e83-00fa1b23b846.png)

I tried using an older version of BR and it works fine but I wanna use the latest version so I can use stageapi stuff in it my outdated stageapi got and I tried reinstalling BR from this git with no avail. I hope it's just an issue in my end and not BR.

**Comment by Zamiell** [comment]
can you test older versions w/ binary search until you find the regression?

**Comment by JudeForNothing** [comment]
It started with the latest version 3.1.48, 3.1.47 and below works just fine

**Comment by Zamiell** [comment]
@guwahavel can you fix your regression

**Comment by budjmt** [comment]
Fixed in https://github.com/Basement-Renovator/basement-renovator/commit/06d86575d9de44c5a3024939934aae2de978bb4c
