### ISSUE TITLE
Autodetection of install path does not work.

### ISSUE THREAD

**Issue by SlawekNowy** [Basement-Renovator/basement-renovator#304]
Autodetection of Binding of Isaac install directory may fail, if that dir is outsice Steam's program files.

steamlibrary.vdf format changed.

**Comment by budjmt** [comment]
I think I see the issue, I'm looking at my `Steam/steamapps/libraryfolders.vdf` file and it seems like paths are presented like this:
```
"0"
	{
		"path"		"C:\\Program Files (x86)\\Steam"
		"label"		""
		"contentid"		"8447123534651498673"
		"totalsize"		"0"
		"update_clean_bytes_tally"		"346388868"
		"time_last_update_corruption"		"0"
		"apps"
		{
			"228980"		"346387987"
		}
	}
```
but the code is expecting a format like `"0" "C:/Path/..."`... I think this new format explains exactly where isaac is installed too.

I still can't run BR, but I'll push up a quick fix, let me know if it works for you
