### ISSUE TITLE
im so dumb pls help

### ISSUE THREAD

**Issue by LIGHTSABNER** [Basement-Renovator/basement-renovator#305]
yo i cannot for the life of me find out how to change the stage and i feel like an idiot

**Comment by Rchardon** [comment]
You will feel more like an idiot when i'll tell you this is a place to report bugs and not a place to ask for help

**Comment by LIGHTSABNER** [comment]
ye ik

**Comment by LIGHTSABNER** [comment]
i too lazy to find out on my own
