### ISSUE TITLE
BR Crashing

### ISSUE THREAD

**Issue by Kostazzz22** [Basement-Renovator/basement-renovator#307]
BR Crashing when I run the room test

**Comment by aspwil** [comment]
seconded, when i try to load a instapreview, it crashes the entire program

traceback:

Traceback (most recent call last):
  File "BasementRenovator.py", line 6287, in testMapInstapreview
  File "BasementRenovator.py", line 6386, in testMapCommon
AttributeError: 'MainWindow' object has no attribute 'floorInfo'

**Comment by aspwil** [comment]
this seems to have resolved itself somehow. maybe because i saved to a file?

**Comment by budjmt** [comment]
Fixed in https://github.com/Basement-Renovator/basement-renovator/commit/06d86575d9de44c5a3024939934aae2de978bb4c
