### ISSUE TITLE
InstaPreview mode deletes save files when entering that save's run

### ISSUE THREAD

**Issue by PixelPlz** [Basement-Renovator/basement-renovator#316]
Opening the game by testing a room in InstaPreview mode and exiting the run (not the game!) will put you in the menu of your last selected save file. If that save file has a run you can continue and you do it in this state, it will completely wipe that save file.

**Comment by budjmt** [comment]
Sorry there's not much we can do about that on the BR side: that aspect of instapreview is implemented by isaac itself. Perhaps repentagon could patch this?
