### ISSUE TITLE
[Suggestion] Add the ability to edit rooms during testing

### ISSUE THREAD

**Issue by yfyfyfyfyfy** [Basement-Renovator/basement-renovator#318]
During testing, a window pops up about disabling the BR Help mod and it prohibits editing rooms in any way. I like to test many rooms at once and it is not very convenient for me that if I find some error/issue/desing problem or want to fix something, I cannot do it immediately without closing the game

**Comment by budjmt** [comment]
You're not the first to run into this; the popup can be disabled by unchecking Test > Enable Test Mod Dialog
